version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: part2-test-backend:latest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vmtf-404516-37748537df37.json
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: part2-test-frontend:latest
    ports:
      - "9000:9000"
    depends_on:
      - backend

volumes:
  postgres_data:
