# Generated by Django 4.2.7 on 2023-11-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_education_api', '0002_alter_comment_username_alter_savedquery_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='username',
            field=models.TextField(),
        ),
    ]
