# Generated by Django 4.2.7 on 2023-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_education_api', '0003_alter_comment_username_alter_savedquery_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
