# Generated by Django 4.2.7 on 2023-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_education_api', '0004_alter_comment_username_alter_savedquery_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedquery',
            name='query_params',
        ),
        migrations.AddField(
            model_name='savedquery',
            name='country_code',
            field=models.CharField(default='USA', max_length=3),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='end_year',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='indicator_code',
            field=models.CharField(default='SE.XPD.TOTL.GD.ZS', max_length=255),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='start_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
