# Generated by Django 4.2.7 on 2023-11-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_education_api', '0005_remove_savedquery_query_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedquery',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='end_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='indicator_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
